# Generated by Django 2.1.4 on 2019-03-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
