# Generated by Django 2.1.4 on 2019-03-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_user_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNum', models.CharField(max_length=128)),
                ('payPassword', models.CharField(max_length=6)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='IDCard',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='realName',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='system.User'),
        ),
    ]
