# Generated by Django 2.1.4 on 2019-03-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20190311_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
