# Generated by Django 2.1.4 on 2019-03-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20190311_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
