# Generated by Django 2.1.4 on 2019-03-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_account_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='binding',
            field=models.BooleanField(default=False),
        ),
    ]
