# Generated by Django 2.1.4 on 2019-03-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_account_binding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.AddField(
            model_name='account',
            name='IDCard',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='realName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
