# Generated by Django 2.1.4 on 2019-03-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20190311_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bindingUser',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
